"""create transacation and bonds

Revision ID: 853779361032
Revises: 005ce6e94401
Create Date: 2022-10-27 16:38:26.291762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853779361032'
down_revision = '005ce6e94401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.Unicode(length=255), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
